### PR TITLE
Update MainModule.lua

### PR DESCRIPTION
**Pull request by ccuser44**
Made the code much cleaner, made it more compact and better optimised as well as fixed a few bugs.

### CODE REVIEW

**Comment by TyNoOutlet** [comment]
I see some helpful changes (xpcall, assert) but this mostly looks like changing variable names, also, what bugs were fixed?

**Review by Developer-Doge — COMMENTED** [review]
AWESOME! Thank you for this, I will have Ty look at it immediately!

**Review by TyNoOutlet — CHANGES_REQUESTED** [review]
Some problems here:

* Remove the output prefix
* Changing all of the variables to PascalCase actually makes the code less readable to me, please keep the variable names the same (or at least in camelCase [except for services], and check your spelling)
* However, I do like the xpcall() and assert() additions. Still am not seeing any bug fixes in here though.

**Comment by TyNoOutlet** [comment]
Closing because a major function is being added. I'll supplement the code by removing testing prints and adding assert() and xpcall() (and will give credit). Open a new pull request if you want to fix anything else.

**Pull request closed without merging**
