### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by ccuser44**
Remade #7

### CODE REVIEW

**Comment by ccuser44** [comment]
This probably should also be added to the script so the script retains its lisence.

**Comment by TyNoOutlet** [comment]
Not all resources on Roblox are public domain. According to the ToS:

"you grant us a perpetual, irrevocable, worldwide, non-exclusive, royalty-free right and license (with the right to sublicense to any person or entity, whether a user of the Service or not) to host, store, transfer, publicly display, publicly perform (including by means of digital audio transmissions and on a through-to-the-audience basis), reproduce (including in timed synchronization to visual images), modify, create derivative works of, distribute, and use in any way the UGC that you Provide, in whole or in part, including modifications and derivative works, in any media or formats (tangible or intangible) and through any media, items or channels (online, offline, or others, now known or hereafter developed), including for publicity and marketing purposes (except that you are not granting us any license to make new or derivative video games using your UGC). Kindly note that if you Provide UGC (such as a catalog item or other items to or for the Service), you do not have the right to remove or modify that UGC (unless Roblox provides tools for you to remove or modify that specific type of UGC, or unless otherwise required by law)."

I believe this license is in conflict with this info:

"Affirmer hereby overtly, fully, permanently, irrevocably and
unconditionally waives, abandons, and surrenders all of Affirmer's Copyright
and Related Rights and associated claims and causes of action, whether now
known or unknown (including existing as well as future claims and causes of
action), in the Work (i) in all territories worldwide, (ii) for the maximum
duration provided by applicable law or treaty (including future time
extensions), (iii) in any current or future medium and for any number of
copies, and (iv) for any purpose whatsoever, including without limitation
commercial, advertising or promotional purposes (the "Waiver"). Affirmer makes
the Waiver for the benefit of each member of the public at large and to the
detriment of Affirmer's heirs and successors, fully intending that such Waiver
shall not be subject to revocation, rescission, cancellation, termination, or
any other legal or equitable action to disrupt the quiet enjoyment of the Work
by the public as contemplated by Affirmer's express Statement of Purpose."

**Comment by ccuser44** [comment]
All content uploaded to Rblx you sublisence to them. It does not mean that the CC0 lisence forces Rblx to use CC0. Sublisencing works fine. But if you don't want to use CC0 then you can use Unlisence which is another public domain lisence and it is more simple and shorter https://choosealicense.com/licenses/unlicense/.

But you absolutely should pick a lisence see https://choosealicense.com/no-permission/ why. 

But if you pick a lisence it is adviced to pick a public domain lisence as it makes the porting of code from github to RBLX easier and removes legal edge cases with free models using it,

**Comment by TyNoOutlet** [comment]
Ok, CC0 will work fine.

**Pull request merged**
